import { MdLocationPin } from "react-icons/md";

// Hindi translations for States names
const hindiStateNames = {
  "Andhra Pradesh": "आंध्र प्रदेश",
  "Arunachal Pradesh": "अरुणाचल प्रदेश",
  Assam: "असम",
  Bihar: "बिहार",
  Chhattisgarh: "छत्तीसगढ़",
  Goa: "गोवा",
  Gujarat: "गुजरात",
  Haryana: "हरियाणा",
  "Himachal Pradesh": "हिमाचल प्रदेश",
  Jharkhand: "झारखंड",
  Karnataka: "कर्नाटक",
  Kerala: "केरल",
  "Madhya Pradesh": "मध्य प्रदेश",
  Maharashtra: "महाराष्ट्र",
  Manipur: "मणिपुर",
  Meghalaya: "मेघालय",
  Mizoram: "मिज़ोरम",
  Nagaland: "नागालैंड",
  Odisha: "ओडिशा",
  Punjab: "पंजाब",
  Rajasthan: "राजस्थान",
  Sikkim: "सिक्किम",
  "Tamil Nadu": "तमिलनाडु",
  Telangana: "तेलंगाना",
  Tripura: "त्रिपुरा",
  "Uttar Pradesh": "उत्तर प्रदेश",
  Uttarakhand: "उत्तराखंड",
  "West Bengal": "पश्चिम बंगाल",
};

// Hindi translations for city names
const hindiCityNames = {
  Gorakhpur: "गोरखपुर",
  Lucknow: "लखनऊ",
  Kanpur: "कानपुर",
  Firozabad: "फिरोजाबाद",
  Agra: "आगरा",
  Meerut: "मेरठ",
  Varanasi: "वाराणसी",
  Allahabad: "इलाहाबाद",
  Amroha: "अमरोहा",
  Moradabad: "मुरादाबाद",
  Aligarh: "अलीगढ़",
  Saharanpur: "सहारनपुर",
  Noida: "नोएडा",
  Loni: "लोनी",
  Jhansi: "झांसी",
  Shahjahanpur: "शाहजहांपुर",
  Rampur: "रामपुर",
  Modinagar: "मोदीनगर",
  Hapur: "हापुड़",
  Etawah: "इटावा",
  Sambhal: "संभल",
  Orai: "ओरई",
  Bahraich: "बहराइच",
  Unnao: "उन्नाव",
  "Rae Bareli": "रायबरेली",
  Lakhimpur: "लखीमपुर",
  Sitapur: "सीतापुर",
  Lalitpur: "ललितपुर",
  Pilibhit: "पीलीभीत",
  Chandausi: "चंदौसी",
  Hardoi: "हरदोई",
  Azamgarh: "आजमगढ़",
  Khair: "खैर",
  Sultanpur: "सुल्तानपुर",
  Tanda: "तांदा",
  Nagina: "नगीना",
  Shamli: "शामली",
  Najibabad: "नजीबाबाद",
  Shikohabad: "शिकोहाबाद",
  Sikandrabad: "सिकंदराबाद",
  "Shahabad, Hardoi": "शाहाबाद, हरदोई",
  Pilkhuwa: "पिलखुवा",
  Renukoot: "रेणुकूट",
  Vrindavan: "वृंदावन",
  Ujhani: "उझानी",
  Laharpur: "लहरपुर",
  Tilhar: "तिलहर",
  Sahaswan: "सहसवान",
  Rath: "राथ",
  Sherkot: "शेरकोट",
  Kalpi: "कालपी",
  Tundla: "टुंडला",
  Sandila: "सांदीला",
  Nanpara: "ननपाड़ा",
  Sardhana: "सरधना",
  Nehtaur: "नेहटौर",
  Seohara: "सेओहरा",
  Padrauna: "पदरौना",
  Mathura: "मथुरा",
  Thakurdwara: "ठाकुरद्वारा",
  Nawabganj: "नवाबगंज",
  Siana: "सियाना",
  Noorpur: "नूरपुर",
  "Sikandra Rao": "सिकंदरा राव",
  Puranpur: "पुरानपुर",
  Rudauli: "रुडौली",
  "Thana Bhawan": "थाना भवान",
  "Palia Kalan": "पालिया कलां",
  Zaidpur: "ज़ैदपुर",
  Nautanwa: "नौतनवा",
  Zamania: "ज़मानिया",
  "Shikarpur, Bulandshahr": "शिकारपुर, बुलंदशहर",
  "Naugawan Sadat": "नौगावां सादात",
  "Fatehpur Sikri": "फ़तेहपुर सीकरी",
  "Shahabad, Rampur": "शाहाबाद, रामपुर",
  Robertsganj: "रोबर्ट्सगंज",
  Utraula: "उत्रौला",
  Sadabad: "सादाबाद",
  Rasra: "रसरा",
  Lar: "लार",
  "Lal Gopalganj Nindaura": "लाल गोपालगंज निंदौरा",
  Sirsaganj: "सिरसागंज",
  Pihani: "पिहानी",
  "Shamsabad, Agra": "शमशाबाद, आगरा",
  Rudrapur: "रूद्रपुर",
  Soron: "सोरोन",
  Samdhan: "समधन",
  Sahjanwa: "सहजनवा",
  "Rampur Maniharan": "रामपुर मनीहारण",
  Sumerpur: "सुमेरपुर",
  Shahganj: "शाहगंज",
  Tulsipur: "तुलसीपुर",
  Tirwaganj: "तीरवागंज",
  Purqazi: "पुरकाज़ी",
  "Shamsabad, Farrukhabad": "शमशाबाद, फर्रुखाबाद",
  Warhapur: "वर्हापुर",
  Powayan: "पोवायन",
  Sandi: "सांडी",
  Achhnera: "अच्छनेरा",
  Naraura: "नरौरा",
  Nakur: "नकुर",
  Sahaspur: "सहसपुर",
  Safipur: "साफीपुर",
  Reoti: "रेवती",
  Sikanderpur: "सिकंदरपुर",
  Saidpur: "सैदपुर",
  Sirsi: "सिरसी",
  Purwa: "पुरवा",
  Parasi: "परासी",
  Phulpur: "फूलपुर",
  Shishgarh: "शीशगढ़",
  Sahawar: "सहवार",
  Samthar: "सामथर",
  Pukhrayan: "पुखरायन",
  Obra: "ओबरा",
  Niwai: "निवाई",
  Mirzapur: "मिर्ज़ापुर",
  Patna: "पटना",
  Gaya: "गया",
  Bhagalpur: "भागलपुर",
  Muzaffarpur: "मुज़फ्फरपुर",
  Darbhanga: "दरभंगा",
  Arrah: "आरा",
  Begusarai: "बेगूसराय",
  Chhapra: "छपरा",
  Katihar: "कटिहार",
  Munger: "मुंगेर",
  Purnia: "पूर्णिया",
  Saharsa: "सहरसा",
  Sasaram: "सासाराम",
  Hajipur: "हाजीपुर",
  "Dehri-on-Sone": "देहरी-ऑन-सोन",
  Bettiah: "बेतिया",
  Motihari: "मोतिहारी",
  Bagaha: "बगहा",
  Siwan: "सीवान",
  Kishanganj: "किशनगंज",
  Jamalpur: "जमालपुर",
  Buxar: "बक्सर",
  Jehanabad: "जहानाबाद",
  Aurangabad: "औरंगाबाद",
  Lakhisarai: "लक्खिसराय",
  Nawada: "नवादा",
  Jamui: "जमुई",
  Sitamarhi: "सीतामढ़ी",
  Araria: "अररिया",
  Gopalganj: "गोपालगंज",
  Madhubani: "मधुबनी",
  Masaurhi: "मसौढ़ी",
  Samastipur: "समस्तीपुर",
  Mokameh: "मोकामेह",
  Supaul: "सुपौल",
  Dumraon: "दुमरावन",
  Arwal: "अरवल",
  Forbesganj: "फॉर्ब्सगंज",
  "BhabUrban Agglomeration": "भाबनगर",
  Narkatiaganj: "नरकटियागंज",
  Naugachhia: "नौगछिया",
  Madhepura: "मधेपुरा",
  Sheikhpura: "शेखपुरा",
  Sultanganj: "सुल्तानगंज",
  "Raxaul Bazar": "रक्सौल बाज़ार",
  Ramnagar: "रामनगर",
  "Mahnar Bazar": "महनार बाज़ार",
  Warisaliganj: "वारिसलीगंज",
  Revelganj: "रेवेलगंज",
  Rajgir: "राजगीर",
  Sonepur: "सोनेपुर",
  Sherghati: "शेरघाटी",
  Sugauli: "सुगौली",
  Makhdumpur: "मख़दूमपुर",
  Maner: "मानेर",
  Rosera: "रोसेरा",
  Nokha: "नोखा",
  Piro: "पीरो",
  Rafiganj: "राफीगंज",
  Marhaura: "मरहौरा",
  Mirganj: "मीरगंज",
  Lalganj: "लालगंज",
  Murliganj: "मुरलीगंज",
  Motipur: "मोतीपुर",
  Manihari: "मनिहारी",
  Sheohar: "शिवहर",
  Maharajganj: "महाराजगंज",
  Silao: "सिलाओ",
  Barh: "बारह",
  Asarganj: "आसरगंज",
};

function CityDisplay({ city, region, condition }) {
  // Check if the city has a Hindi translation
  const cityInHindi = hindiCityNames[city] || city;
  const stateInHindi = hindiStateNames[region] || region;

  const conditionTranslations = {
    Sunny: "धूप",
    Mist: "धुंध",
    Rain: "बारिश",
    Cloudy: "बादल",
    "Patchy rain nearby": "नजदीक हल्की बारिश",
    Overcast: "आसमान में बादल",
    "Partly cloudy": "आंशिक रूप से बादल",
    "Light rain": "हल्की बारिश",
    "Heavy rain": "तेज़ बारिश",
    Thunderstorm: "बिजली गरजना",
    Clear: "स्पष्ट",
    Snow: "बर्फ़",
  };

  return (
    <div className="flex items-center justify-center my-4">
      <div className="flex flex-col items-center">
        {/* City and Country Information */}
        <h2 className="text-3xl font-medium flex items-center gap-2">
          <MdLocationPin /> {cityInHindi}, {stateInHindi}
        </h2>
        {/* Weather Condition Text */}
        <p className="text-md text-gray-600">
          {" "}
          {conditionTranslations[condition.text] || condition.text}
        </p>
      </div>
    </div>
  );
}

export default CityDisplay;
